services:
  mariadb:
    build: requirements/mariadb
    env_file: .env
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    build: requirements/wordpress
    env_file: .env
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
    volumes:
      - wordpress_data:/var/www/html

  nginx:
    build: requirements/nginx
    env_file: .env
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    restart: always
    volumes:
      - wordpress_data:/var/www/html

volumes:
  mariadb_data:
    name: inception_mariadb_data
  wordpress_data:
    name: inception_wordpress_data

networks:
  inception:
