services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}

  nginx:
    build: requirements/nginx
    container_name: nginx
    env_file: .env
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception
    restart: always

volumes:
  mariadb_data:
    name: inception_mariadb_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_MARIA}

  wordpress_data:
    name: inception_wordpress_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_WORDPRESS}

networks:
  inception:
    name: inception
    driver: bridge
